### ISSUE TITLE
Lots of non-REST APIs

### ISSUE THREAD

**Issue by kephas** [marmelab/awesome-rest#146]
A lot of the APIs listed here don't have any capability to use HATEOAS, and that's a central requirement to do REST.

Maybe this could be split between awesome-http-api and awesome-rest?

**Comment by kephas** [comment]
Or at least a first section for the truly REST software and documents and a separate page/section for everything that's Level 2 of the RMM…

**Comment by fzaninotto** [comment]
No, HATEOAS isn't a central requirement of REST. The RMM is dogma.

**Comment by kephas** [comment]
It says differently in Roy Fieldings's PhD thesis where he defines REST, in [section 5.1.5](https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm#sec_5_1_5):

> REST is defined by four interface constraints: identification of resources; manipulation of resources through representations; self-descriptive messages; and, **hypermedia as the engine of application state**.

He reiterated the fact several years later: ["REST APIs must be hypertext-driven"](https://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven).
