### ISSUE TITLE
Open source alternative to RequestBin

### ISSUE THREAD

**Issue by darklynx** [marmelab/awesome-rest#56]
Hi,

I'd like to advertise a little bit my own service (https://github.com/darklynx/request-baskets), which is a feature reach open source alternative to RequestBin service.

Would you be so kind to add to your collection, should I create a PR, or it does not fit here due for some reason (e.g. duplicates functionality presented by other software)?

Regards,
darklynx

**Comment by fzaninotto** [comment]
Hi,

Feel free to open a PR to add your service.
